### ISSUE TITLE
`mobie hcs` seems to fail - currenlty

### ISSUE THREAD

**Issue by k-dominik** [mobie/mobie-cmd#4]
```bash
$ mobie hcs
Exception in thread "main" picocli.CommandLine$DuplicateOptionAnnotationsException: Option name '-h' is used by both field boolean picocli.CommandLine$AutoHelpMixin.helpRequested and field String org.embl.mobie.cmd.HCSCmd.hcs
	at picocli.CommandLine$DuplicateOptionAnnotationsException.create(CommandLine.java:16718)
	at picocli.CommandLine$DuplicateOptionAnnotationsException.access$2000(CommandLine.java:16712)
	at picocli.CommandLine$Model$CommandSpec.addOption(CommandLine.java:6081)
	at picocli.CommandLine$Model$CommandSpec.addMixin(CommandLine.java:6337)
	at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:6621)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:10607)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5765)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.<init>(CommandLine.java:196)
	at org.embl.mobie.cmd.HCSCmd.main(HCSCmd.java:77)
```

**Comment by tischi** [comment]
Thanks I fixed it in 4.0.3
I will trigger a pypi release with that soon.
